apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels: {{- include "rustfs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: ui
      protocol: TCP
      name: ui
  selector: {{- include "rustfs.selectorLabels" . | nindent 4 }}
